version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: events_db
      DB_PORT: 5432
      DB_SSLMODE: disable
      DB_TIMEZONE: UTC
    ports:
      - "8080:8080"
      - "2345:2345"
    volumes:
      - ./tmp/uploads:/app/uploads
      - .:/app
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
